### ISSUE TITLE
Vector class with all vector operations

### ISSUE THREAD

**Issue by fl-fernandes** [FlavioLucasFer/jumping-dinosaur#3]
Physics vector, not the data structure

Reference:

- [https://github.com/ehmcruz/zeh-muamba/blob/master/vector.h](https://github.com/ehmcruz/zeh-muamba/blob/master/vector.h)
- [https://github.com/ehmcruz/zeh-muamba/blob/master/vector.cpp](https://github.com/ehmcruz/zeh-muamba/blob/master/vector.cpp)

**Comment by CbNavarro** [comment]
closed
